[package]
name = "android_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = { version = "0.21", default-features = false }
vaultwarden = { path = "../../" }

[workspace]
